# Agentless Collection Configuration

# Syslog server configuration
syslog:
  enabled: true
  host: "0.0.0.0"  # Listen on all interfaces
  port: 514         # Default Syslog port
  protocol: "udp"   # udp or tcp
  
  # Message processing
  max_message_size: 65535  # Maximum message size in bytes
  timeout: 5.0             # Connection timeout in seconds
  
  # Advanced settings
  reuse_port: true
  backlog: 100             # Maximum number of queued connections
  
  # Logging
  log_level: "INFO"        # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Message filtering (optional)
  filters:
    - type: "severity"
      operator: "<="
      value: 5  # Only process messages with severity <= 5 (notice)
    
    # Example: Filter out specific hosts
    # - type: "hostname"
    #   operator: "not in"
    #   value: ["spam-host-1", "spam-host-2"]

# SNMP Trap configuration
snmp_trap:
  enabled: true
  host: "0.0.0.0"  # Listen on all interfaces
  port: 162        # Default SNMP trap port
  
  # SNMP version (1, 2c, or 3)
  version: "2c"
  
  # Community string (for SNMP v1/v2c)
  community: "public"
  
  # SNMP v3 specific settings
  username: "trapuser"
  auth_key: "authpass"
  priv_key: "privpass"
  
  # Logging
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Trap filtering (optional)
  filters:
    # Example: Filter by OID prefix
    # - type: "oid_prefix"
    #   value: "1.3.6.1.4.1"  # Only process enterprise-specific traps
    
    # Example: Filter by source IP
    # - type: "source_ip"
    #   operator: "not in"
    #   value: ["10.0.0.1", "192.168.1.1"]

# Windows Event Forwarding (WEF) configuration
windows_event_forwarding:
  enabled: true  # Enable WEF collection
  host: "localhost"  # WEF server hostname or IP (localhost for local machine)
  port: 5985  # Default WEF port (WinRM HTTP)
  use_https: false  # Set to true for HTTPS/WinRM over SSL
  auth_type: "ntlm"  # ntlm or kerberos
  username: ""  # Leave empty for current user (NTLM) or specify in format 'DOMAIN\\username'
  password: ""  # Leave empty for current user (NTLM) or provide password
  
  # Subscription settings
  subscription_name: "SIEM-Collector-Subscription"
  subscription_expiry: 3600  # Subscription expiry in seconds (1 hour)
  heartbeat_interval: 60  # Heartbeat interval in seconds
  
  # Event filtering (XPath query)
  query: |
    <QueryList>
      <Query Id="0" Path="Application">
        <Select Path="Application">*[System[(Level=1 or Level=2 or Level=3)]]</Select>
      </Query>
      <Query Id="1" Path="Security">
        <Select Path="Security">*</Select>
      </Query>
      <Query Id="2" Path="System">
        <Select Path="System">*[System[(Level=1 or Level=2 or Level=3)]]</Select>
      </Query>
    </QueryList>
  
  # Logging
  log_level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# NetFlow/sFlow configuration (future)
# netflow:
#   enabled: false
#   port: 2055  # Default NetFlow port
#   
# sflow:
#   enabled: false
#   port: 6343  # Default sFlow port
