snmp:
  auth_key: ''
  auth_protocol: SHA
  community: public
  enabled: false
  host: 0.0.0.0
  port: 162
  priv_key: ''
  priv_protocol: AES
  username: ''
  version: 2c
syslog:
  enabled: true
  format: ''
  host: 0.0.0.0
  port: 514
  protocol: udp
windows_event_forwarding:
  domain: ''
  enabled: true
  password: ''
  query: "<QueryList>\n  <Query Id=\"0\" Path=\"Application\">\n    <Select Path=\"\
    Application\">*[System[(Level=1 or Level=2 or Level=3)]]</Select>\n  </Query>\n\
    \  <Query Id=\"1\" Path=\"Security\">\n    <Select Path=\"Security\">*</Select>\n\
    \  </Query>\n  <Query Id=\"2\" Path=\"System\">\n    <Select Path=\"System\">*[System[(Level=1\
    \ or Level=2 or Level=3)]]</Select>\n  </Query>\n</QueryList>\n"
  server: ''
  username: ''
