# Malware Response Playbook
id: malware_response
name: Malware Infection Response
description: Automated response to detected malware infections
enabled: true
min_severity: MEDIUM
required_tags: [malware, c2]

actions:
  # Block the malicious IP
  - type: block_ip
    target: "{{ alert.source_ip }}"
    parameters:
      duration: "24h"
      reason: "Malware C2 communication detected"
    priority: 100
    enabled: true

  # Quarantine the infected device
  - type: quarantine_device
    target: "{{ alert.source_ip }}"
    parameters:
      vlan: 999
      duration: "8h"
      reason: "Malware infection detected"
    priority: 90
    enabled: true

  # Notify SOC team
  - type: webhook
    target: "https://soc.example.com/api/alerts"
    parameters:
      method: POST
      headers:
        Authorization: "Bearer ${API_KEY}"
        Content-Type: "application/json"
      payload:
        alert_id: "{{ alert.id }}"
        title: "Malware Infection Detected"
        severity: "{{ alert.severity }}"
        source_ip: "{{ alert.source_ip }}"
        description: "{{ alert.description }}"
        action: "Device quarantined and IP blocked"
    priority: 80
    enabled: true
