# Compliance Manager Configuration

# Audit logging configuration
audit_config:
  log_dir: "logs/audit"
  retention_days: 365
  max_size_mb: 100

# Report configurations
reports:
  # GDPR Compliance Report - Runs daily at midnight
  - id: "gdpr_daily"
    type: "gdpr"
    name: "GDPR Daily Compliance Report"
    description: "Daily report of data access and processing activities for GDPR compliance"
    output_dir: "reports/gdpr"
    retention_days: 90
    schedule:
      enabled: true
      frequency: "daily"
      time: "00:00"
      run_on_startup: true
    
  # HIPAA Compliance Report - Runs weekly on Sunday at 1:00 AM
  - id: "hipaa_weekly"
    type: "hipaa"
    name: "HIPAA Weekly Compliance Report"
    description: "Weekly report of PHI access and security incidents for HIPAA compliance"
    output_dir: "reports/hipaa"
    retention_days: 180
    schedule:
      enabled: true
      frequency: "weekly"
      day: "sunday"
      time: "01:00"
    
  # PCI-DSS Compliance Report - Runs monthly on the 1st at 2:00 AM
  - id: "pcidss_monthly"
    type: "pcidss"
    name: "PCI-DSS Monthly Compliance Report"
    description: "Monthly report of cardholder data access and security controls for PCI-DSS compliance"
    output_dir: "reports/pcidss"
    retention_days: 365
    schedule:
      enabled: true
      frequency: "monthly"
      day: 1  # 1st of the month
      time: "02:00"
    
  # ISO 27001 Compliance Report - Runs quarterly on the 1st at 3:00 AM
  - id: "iso27001_quarterly"
    type: "iso27001"
    name: "ISO 27001 Quarterly Compliance Report"
    description: "Quarterly report of information security controls and risk management for ISO 27001 compliance"
    output_dir: "reports/iso27001"
    retention_days: 730  # 2 years
    schedule:
      enabled: true
      frequency: "quarterly"
      day: 1  # 1st of the quarter
      time: "03:00"
      run_on_startup: false

  # SOX Compliance Report - Runs quarterly on the 1st at 4:00 AM
  - id: "sox_quarterly"
    type: "sox"
    name: "SOX Quarterly Compliance Report"
    description: "Quarterly report of financial controls and access management for SOX compliance"
    output_dir: "reports/sox"
    retention_days: 730  # 2 years
    schedule:
      enabled: true
      frequency: "monthly"
      day: 1  # 1st of the month
      time: "03:00"
      months: [1, 4, 7, 10]  # Run quarterly
    
  # Custom Security Report - Runs on demand only
  - id: "security_audit"
    type: "gdpr"  # Using GDPR as base but can be customized
    name: "Security Audit Report"
    description: "On-demand security audit report"
    output_dir: "reports/security"
    retention_days: 365
    schedule:
      enabled: false  # Disable automatic scheduling
