# DLP (Data Loss Prevention) Configuration

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/dlp.log"

# DLP specific configuration
dlp:
  # General settings
  host: "0.0.0.0"
  port: 5004
  debug: false
  
  # Scanning settings
  scanning:
    # File system scanning
    filesystem:
      enabled: true
      scan_interval: 3600  # seconds
      scan_paths:
        - "/home"
        - "/data"
      excluded_paths:
        - "/home/*/temp"
        - "/tmp"
      
    # Network traffic scanning
    network:
      enabled: true
      interfaces: ["eth0", "en0"]
      
    # Email scanning
    email:
      enabled: true
      protocols: ["smtp", "imap", "pop3"]
      
    # Web traffic scanning
    web:
      enabled: true
      protocols: ["http", "https"]
      
  # Detection rules
  rules:
    # Credit card numbers
    - name: "credit_card"
      description: "Detect credit card numbers"
      pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11})\\b"
      severity: "high"
      action: "block"
      
    # Social Security Numbers (US)
    - name: "ssn"
      description: "Detect US Social Security Numbers"
      pattern: "\\b\\d{3}[-.]?\\d{2}[-.]?\\d{4}\\b"
      severity: "high"
      action: "alert"
      
    # API keys
    - name: "api_key"
      description: "Detect potential API keys"
      pattern: "(?i)(?:key|api|token|secret)[:=]\\s*[a-z0-9]{20,}"
      severity: "medium"
      action: "alert"
  
  # Response actions
  response:
    # Email notification
    email:
      enabled: true
      smtp_host: "smtp.example.com"
      smtp_port: 587
      smtp_user: "dlp@example.com"
      smtp_password: "your-password"
      from_email: "dlp-alerts@yourdomain.com"
      to_emails: ["security-team@yourdomain.com"]
      
    # Webhook notification
    webhook:
      enabled: false
      url: "https://your-webhook-url.com/dlp-alert"
      
    # Quarantine settings
    quarantine:
      enabled: true
      path: "/var/dlp/quarantine"
      
  # Integration with SIEM
  siem:
    enabled: true
    host: "localhost"
    port: 5001
    
  # API settings
  api:
    enabled: true
    host: "0.0.0.0"
    port: 5004
    secret_key: "your-dlp-secret-key-here"
    
  # Update settings
  updates:
    enabled: true
    check_interval: 86400  # seconds (24 hours)
    url: "https://updates.your-dlp.com"
