# DLP Policy Templates
# These templates demonstrate how to define DLP policies for different scenarios.

# 1. Block sensitive data in emails
block_sensitive_emails:
  id: "email_sensitive_data_block"
  name: "Block Emails with Sensitive Data"
  description: "Prevent emails containing sensitive information from being sent"
  scope: ["email"]
  rules:
    - id: "block_ssn_in_email"
      name: "Block SSN in Email"
      conditions:
        - type: "pattern_match"
          field: "content"
          pattern: "\\b\\d{3}[-.]?\\d{2}[-.]?\\d{4}\\b"
          sensitivity: "high"
      actions:
        - type: "block"
          params:
            message: "Email contains sensitive information (SSN)"
        - type: "notify"
          params:
            recipients: ["security@example.com"]
            subject: "Blocked email with sensitive data"

# 2. Encrypt sensitive files on endpoints
encrypt_sensitive_files:
  id: "endpoint_encrypt_sensitive"
  name: "Encrypt Sensitive Files on Endpoints"
  description: "Automatically encrypt files containing sensitive data on endpoints"
  scope: ["endpoint"]
  rules:
    - id: "encrypt_sensitive_content"
      name: "Encrypt Files with Sensitive Data"
      conditions:
        - type: "pattern_match"
          field: "content"
          pattern: "\\b(?:credit.*card|ssn|social.*security|password)"
          sensitivity: "high"
      actions:
        - type: "encrypt"
          params:
            algorithm: "AES-256"
        - type: "log"
          params:
            message: "Encrypted file containing sensitive data"

# 3. Quarantine unauthorized file transfers
quarantine_unauthorized_transfers:
  id: "network_quarantine_transfers"
  name: "Quarantine Unauthorized File Transfers"
  description: "Quarantine files being transferred to unauthorized locations"
  scope: ["network"]
  rules:
    - id: "block_external_transfers"
      name: "Block External File Transfers"
      conditions:
        - type: "destination_match"
          field: "destination"
          pattern: "(external\.|dropbox|googledrive|onedrive)"
      actions:
        - type: "quarantine"
          params:
            quarantine_dir: "/var/quarantine"
        - type: "notify"
          params:
            recipients: ["security@example.com"]
            subject: "Unauthorized file transfer blocked"

# 4. Redact sensitive information in cloud storage
redact_cloud_data:
  id: "cloud_redact_sensitive"
  name: "Redact Sensitive Data in Cloud Storage"
  description: "Automatically redact sensitive information in cloud storage"
  scope: ["cloud"]
  rules:
    - id: "redact_credit_cards"
      name: "Redact Credit Card Numbers"
      conditions:
        - type: "pattern_match"
          field: "content"
          pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})\\b"
          sensitivity: "high"
      actions:
        - type: "redact"
          params:
            replacement: "[REDACTED]"
        - type: "log"
          params:
            message: "Redacted credit card information from cloud storage"

# 5. Monitor and log sensitive data access
monitor_sensitive_access:
  id: "monitor_sensitive_access"
  name: "Monitor Access to Sensitive Data"
  description: "Log all access to sensitive data for auditing purposes"
  scope: ["all"]
  rules:
    - id: "log_sensitive_access"
      name: "Log Sensitive Data Access"
      conditions:
        - type: "sensitivity_level"
          level: "high"
      actions:
        - type: "log"
          params:
            message: "Sensitive data accessed"
            level: "info"
        - type: "notify"
          params:
            recipients: ["audit@example.com"]
            subject: "Sensitive data access detected"
            threshold: 5  # Only notify after 5 occurrences per hour
