# EDR Agent Configuration

# SIEM Integration
siem:
  endpoint: "http://localhost:5000/api/alerts"  # Update with your SIEM endpoint
  api_key: ""  # Optional API key for authentication
  verify_ssl: true  # Verify SSL certificate

# Agent Configuration
agent:
  check_interval: 60  # seconds between checks
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  # Logging is now handled by the centralized logging system in logs/siem.log
  
# Detection Settings
detection:
  # Process monitoring
  monitor_processes: true
  suspicious_keywords:
    - "powershell -nop -c"
    - "iex"
    - "nishang"
    - "mimikatz"
    - "-enc"  # Encoded command
  
  # Network monitoring
  monitor_network: true
  suspicious_ports:
    - 4444  # Common C2 port
    - 8080  # Common C2 port
    - 9001  # Common C2 port
    - 22    # SSH
    - 23    # Telnet
    - 3389  # RDP
  
  # File system monitoring (future use)
  monitor_files: false
  watch_directories:
    - "C:\\Windows\\System32"
    - "C:\\Program Files"
    - "C:\\ProgramData"

# Alerting
alert:
  # Email notifications (future use)
  email_enabled: false
  email_recipients: []
  email_smtp_server: "smtp.example.com"
  email_smtp_port: 587
  email_smtp_user: ""
  email_smtp_password: ""
  
  # Webhook notifications (future use)
  webhook_enabled: false
  webhook_url: ""

# Whitelisting (future use)
whitelist:
  processes: []
  ips: []
  domains: []
