# HIPS (Host-based Intrusion Prevention System) Configuration

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/hips.log"

# HIPS specific configuration
hips:
  # General settings
  host: "0.0.0.0"
  port: 5006
  debug: false
  
  # Monitoring settings
  monitoring:
    # Process monitoring
    process:
      enabled: true
      scan_interval: 60  # seconds
      
    # Registry monitoring (Windows)
    registry:
      enabled: true
      scan_interval: 300  # seconds
      
    # File system monitoring
    filesystem:
      enabled: true
      scan_interval: 300  # seconds
      excluded_paths:
        - "/System/Volumes/Data/System"
        - "/proc"
        - "/sys"
        - "/dev"
      
    # Network monitoring
    network:
      enabled: true
      
  # Protection settings
  protection:
    # Memory protection
    memory:
      enabled: true
      
    # Exploit mitigation
    exploit_mitigation:
      enabled: true
      
    # Ransomware protection
    ransomware_protection:
      enabled: true
      
  # Rules
  rules:
    # Suspicious process execution
    - name: "suspicious_process_execution"
      description: "Detect execution of suspicious processes"
      type: "process"
      patterns:
        - "*\temp\*"
        - "*\appdata\local\temp\*"
        - "/tmp/*"
      action: "alert"
      severity: "high"
      
    # Unauthorized registry changes
    - name: "unauthorized_registry_changes"
      description: "Detect unauthorized changes to critical registry keys"
      type: "registry"
      keys:
        - "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
        - "HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      action: "block"
      severity: "high"
  
  # Response actions
  response:
    # Process termination
    terminate_process:
      enabled: true
      
    # Network isolation
    network_isolation:
      enabled: true
      
    # File quarantine
    quarantine:
      enabled: true
      path: "/var/hips/quarantine"
  
  # Integration with SIEM
  siem:
    enabled: true
    host: "localhost"
    port: 5001
    
  # API settings
  api:
    enabled: true
    host: "0.0.0.0"
    port: 5006
    secret_key: "your-hips-secret-key-here"
    
  # Update settings
  updates:
    enabled: true
    check_interval: 3600  # seconds
    url: "https://updates.your-hips.com"
    
  # Alerting settings
  alerting:
    email:
      enabled: false
      smtp_host: "smtp.example.com"
      smtp_port: 587
      smtp_user: "hips@example.com"
      smtp_password: "your-password"
      from_email: "hips-alerts@yourdomain.com"
      to_emails: ["security-team@yourdomain.com"]
    
    # Webhook for alert notifications
    webhook:
      enabled: false
      url: "https://your-webhook-url.com/hips-alert"
