# Log Sources Configuration
# Defines various log sources for the SIEM system

# File-based log sources
file_logs:
  - name: "auth_logs"
    type: "file"
    path: "/var/log/auth.log"
    batch_size: 100
    
  - name: "application_logs"
    type: "file"
    path: "/var/log/application/application.log"
    batch_size: 50

# Syslog sources
syslog_sources:
  - name: "network_devices"
    type: "syslog"
    host: "0.0.0.0"
    port: 514
    protocol: "udp"

# Windows Event Log (future implementation)
windows_event_logs:
  - name: "security_logs"
    type: "windows_event"
    log_name: "Security"
    level: "information"

# Cloud Services (future implementation)
cloud_sources:
  - name: "aws_cloudtrail"
    type: "aws_cloudtrail"
    region: "us-east-1"
    log_group: "CloudTrail/DefaultLogGroup"

# Database Logs (future implementation)
database_logs:
  - name: "postgresql_logs"
    type: "postgresql"
    host: "localhost"
    port: 5432
    database: "postgres"
    username: "monitor"

# Web Server Logs (future implementation)
web_server_logs:
  - name: "nginx_access"
    type: "nginx"
    path: "/var/log/nginx/access.log"
    format: "combined"

# Firewall Logs (future implementation)
firewall_logs:
  - name: "pfsense_firewall"
    type: "pfsense"
    host: "firewall.local"
    protocol: "https"
    api_key: "${PFSENSE_API_KEY}"  # Use environment variable

# IDS/IPS Logs (future implementation)
ids_ips_logs:
  - name: "suricata_alerts"
    type: "suricata"
    eve_log_path: "/var/log/suricata/eve.json"

# Authentication Logs (future implementation)
auth_logs:
  - name: "active_directory"
    type: "active_directory"
    domain: "example.com"
    username: "${AD_USERNAME}"  # Use environment variable
    password: "${AD_PASSWORD}"  # Use environment variable

# Endpoint Logs (future implementation)
endpoint_logs:
  - name: "windows_endpoints"
    type: "windows_event_forwarding"
    subscription_url: "https://endpoint1.example.com/wsman"
    auth_type: "kerberos"

# Custom Application Logs (future implementation)
custom_logs:
  - name: "custom_app"
    type: "custom"
    parser: "custom_app_parser"
    source: "/var/log/custom/app.log"

# Configuration for log rotation and retention
log_retention:
  enabled: true
  max_size_mb: 100
  backup_count: 5
  compression: "gzip"
  retention_days: 30

# Global log processing settings
processing:
  timezone: "UTC"
  batch_size: 100
  max_workers: 4
  queue_size: 1000

# Field mappings for log normalization
field_mappings:
  timestamp:
    - "@timestamp"
    - "timestamp"
    - "time"
    - "date"
  source_ip:
    - "src_ip"
    - "source_address"
    - "client_ip"
  destination_ip:
    - "dst_ip"
    - "destination_address"
    - "server_ip"
  username:
    - "user"
    - "username"
    - "user_name"

# Alert thresholds
alert_thresholds:
  failed_logins: 5  # Number of failed logins before alert
  port_scan: 20     # Number of connection attempts to different ports
  brute_force: 10   # Number of authentication attempts to the same account

# Default fields to extract and index
indexed_fields:
  - "@timestamp"
  - "source_ip"
  - "destination_ip"
  - "event_type"
  - "severity"
  - "username"
  - "action"
  - "status"

# Enrichment settings (future implementation)
enrichment:
  geoip: true
  dns_lookup: true
  threat_intel: true
  asset_db: true
