# Monitoring Service Configuration

# Metrics configuration
metrics:
  # Exporters for metrics
  exporters:
    # Console exporter (for debugging)
    - type: console
      format: text  # or 'json'
      
    # Prometheus exporter
    - type: prometheus
      port: 9090
      path: /metrics

# Alerting configuration
alerts:
  # Global alert settings
  settings:
    default_severity: MEDIUM
    throttle_seconds: 300  # Minimum time between alerts for the same rule
    
  # Alert rules
  rules:
    # Example: High error rate
    - name: high_error_rate
      type: threshold
      description: "Error rate exceeds 10%"
      metric: "siem.errors.rate"
      threshold: 0.1
      severity: HIGH
      labels:
        component: "siem"
        type: "performance"
      annotations:
        summary: "High error rate detected"
        runbook: "Check SIEM logs for errors and review system health"
    
    # Example: High processing latency
    - name: high_processing_latency
      type: threshold
      description: "Event processing latency is too high"
      metric: "siem.processing.latency.95p"
      threshold: 1000  # ms
      severity: MEDIUM
      labels:
        component: "siem"
        type: "performance"

# Health check configuration
health_checks:
  # System resource checks
  system:
    cpu:
      warning: 80  # %
      critical: 90  # %
    memory:
      warning: 80  # %
      critical: 90  # %
    disk:
      paths:
        - path: "/"
          warning: 80  # % used
          critical: 90  # % used
  
  # Service health checks
  services:
    # Database connection
    - name: "database_connection"
      type: tcp
      host: "localhost"
      port: 5432
      interval: 60  # seconds
      
    # API endpoint
    - name: "api_health"
      type: http
      url: "http://localhost:8000/health"
      expected_status: 200
      interval: 30  # seconds

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "/var/log/siem/monitoring.log"
  max_size: 10485760  # 10 MB
  backup_count: 5
