# SIEM Configuration

# Logging configuration
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "D:/security.operations.center/logs/siem.log"

# SIEM specific configuration
siem:
  # General settings
  host: "0.0.0.0"
  port: 5000
  debug: true
  
  # Data retention (in days)
  retention_days: 30
  
  # Correlation engine settings
  correlation:
    enabled: true
    rules_path: "D:/security.operations.center/rules/correlation_rules"
    
  # Monitoring service settings
  monitoring:
    enabled: true
    interval: 60  # seconds
    
  # Log collector settings
  log_collector:
    enabled: true
    log_dirs:
      - "D:/security.operations.center/logs"
    file_patterns:
      - "*.log"
      
  # EDR settings
  edr:
    enabled: true
    server_enabled: true
    
  # NIPS settings
  nips:
    enabled: true
    
  # Compliance settings
  compliance:
    enabled: true
    
  # Storage settings
  storage:
    type: "sqlite"  # Options: sqlite, postgresql, mysql
    database: "D:/security.operations.center/data/siem.db"
    max_connections: 10
    timeout: 30  # seconds
    
  # API settings
  api:
    enabled: true
    host: "0.0.0.0"
    port: 5001
    secret_key: "your-secret-key-here"
    
  # Alerting settings
  alerting:
    email:
      enabled: false
      smtp_host: "smtp.example.com"
      smtp_port: 587
      smtp_user: "user@example.com"
      smtp_password: "your-password"
      from_email: "alerts@yourdomain.com"
      to_emails: ["admin@yourdomain.com"]
    
    # Webhook for alert notifications
    webhook:
      enabled: false
      url: "https://your-webhook-url.com/alert"
      
  # Log sources configuration
  log_sources:
    - name: "windows_events"
      type: "windows_event_log"
      enabled: true
      channels: ["Security", "System", "Application"]
      
    - name: "syslog"
      type: "syslog"
      enabled: true
      listen_address: "0.0.0.0"
      port: 514
      protocol: "udp"  # udp or tcp
      
  # Integration with other components
  integrations:
    edr:
      enabled: true
      host: "localhost"
      port: 5002
      
    nips:
      enabled: true
      host: "localhost"
      port: 5003
