# Storage configuration for historical data

# Base directory for all storage
data_dir: "data/storage"

# Maximum number of worker threads for background tasks
max_workers: 8

# Default compression settings
default_compression: "zstd"  # Options: zstd, gzip, none

# Retention policies by data type
retention_policies:
  # Raw logs and events
  raw_events:
    hot_days: 7      # Keep in hot storage for 7 days
    warm_days: 30    # Move to warm storage after 7 days
    cold_days: 90    # Move to cold storage after 30 days
    archive_days: 365 # Archive after 90 days, delete after 1 year
    compression: "zstd"
  
  # Aggregated metrics and statistics
  metrics:
    hot_days: 30
    warm_days: 90
    cold_days: 365
    archive_days: 1825  # 5 years
    compression: "zstd"
  
  # Compliance reports
  reports:
    hot_days: 30
    warm_days: 180
    cold_days: 1095  # 3 years
    archive_days: 3650  # 10 years
    compression: "gzip"
  
  # Audit logs
  audit_logs:
    hot_days: 30
    warm_days: 90
    cold_days: 365
    archive_days: 1825  # 5 years
    compression: "zstd"

# Lifecycle management settings
lifecycle:
  # How often to run the lifecycle management (in hours)
  run_interval_hours: 24
  
  # Maximum age (in days) to keep temporary files
  max_temp_file_age_days: 1
  
  # Enable/disable automatic cleanup of expired data
  enable_cleanup: true

# Integrity checking settings
integrity:
  # Verify checksums on read
  verify_on_read: true
  
  # Periodically verify all data (in days, 0 to disable)
  full_scan_interval_days: 7
  
  # Automatically repair corrupted files if possible
  auto_repair: true

# Performance settings
performance:
  # Size of read/write buffers (in bytes)
  buffer_size: 65536  # 64KB
  
  # Maximum size of in-memory cache (in MB)
  max_memory_cache_mb: 1024
  
  # Compression level (1-22 for zstd, 1-9 for gzip)
  compression_level: 3

# Monitoring settings
monitoring:
  # Enable Prometheus metrics
  enable_metrics: true
  
  # Metrics endpoint port
  metrics_port: 9091
  
  # Log storage usage statistics
  log_usage_stats: true
  
  # How often to log statistics (in minutes)
  stats_log_interval_minutes: 60
